image: woohuiren/php-laravel-env:latest

services:
  - mysql:latest

before_script:
  - sh .gitlab-key-inject.sh # Script injection for SSH keys used for deployments

variables:
  MYSQL_DATABASE: laravel
  MYSQL_ROOT_PASSWORD: secret
  SSH_PRIVATE_KEY: somethingsomethingblahblah # Recommended to put into GitLab secret variables instead
  GIT_DEPLOYMENT_REMOTE: origin
  GIT_DEPLOYMENT_BRANCH: master
  STAGING_SERVER_HOSTNAME: admin@localhost
  STAGING_SERVER_DIRECTORY: /home/admin/laravel-project/public

stages:
  - build
  - test
  - staging_deploy

build_job:
  stage: build
  script:
    - sh .gitlab-build.sh
  artifacts:
    paths:
      - vendor/
      - bootstrap/
      - composer.phar
      - .env
  tags:
    - docker

test_job:
  stage: test
  dependencies:
    - build_job
  script:
    - sh .gitlab-test.sh
  tags:
    - docker

stage_job:
  stage: staging_deploy
  script:
    - sh .gitlab-staging-pull-deploy.sh
  environment:
    name: staging